name: Semgrep Security Scan

on:
  # Run on push to main/master branches
  push:
    branches:
      - main
      - master
  # Run on pull requests
  pull_request: {}
  # Allow manual trigger
  workflow_dispatch: {}

jobs:
  semgrep:
    name: Scan with Semgrep
    runs-on: ubuntu-latest
    
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    
    container:
      # Use Semgrep Docker image for consistency
      image: semgrep/semgrep
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Semgrep
        run: |
          semgrep scan \
            --config=auto \
            --config=.semgrep.yml \
            --exclude="build/" \
            --exclude="bin/" \
            --exclude=".gradle/" \
            --sarif \
            --output=semgrep-results.sarif \
            src/
        
        # Continue even if Semgrep finds issues (report them but don't fail)
        continue-on-error: true
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif
        if: always()

